[tool.poetry]
name = "nephelaiio.acme_certificate_cloudflare"
version = "0.1.0"
description = ""
authors = ["Ted Cook <teodoro.cook@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
tox = "^3.25.0"
ansible-lint = "~5"
yamllint = "^1.27.1"
ansible = "^6.1.0"
MarkupSafe = "2.0.1"
molecule = {extras = ["docker"], version = "^4.0.4"}

[tool.poetry.group.dev.dependencies]
netaddr = "^0.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
