---
name: CI Keepalive

on:
  schedule:
    - cron: "55 23 * * 4"

jobs:
  keepalive:
    name: Github Actions keepalive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@master
        with:
          commit_message: "CI Keepalive"
          committer_username: "teddyphreak"
          committer_email: "teodoro.cook@gmail.com"
          auto_push: true
